title: jasinobe
description: blog
author: Jasmeet Oberai

email: me@jasmeetoberai.com
github: jasmeeto
linkedin: jasoberai
facebook: jas.oberai
twitter: JasmeetOberai
website: www.jasmeetoberai.com

name: jasmeetoberai
highlighter: rouge
